### ISSUE TITLE
Solidity: Create a contract that generates CRTV tokens

### ISSUE THREAD

**Issue by gawainb** [g2entgroup/didactic-garbanzo#15]
Create a contract that generates ERC20 tokens.
Creative Token
"CRTV"
Total Supply: 980,000,000

**Comment by Tanteli** [comment]
Do you mean ERC20 tokens ?

**Comment by gawainb** [comment]
@Tanteli correct these will be ERC20 tokens.

**Comment by gawainb** [comment]
I have a working contract now that generates Creative (CRTV) tokens.
The functions include:

- Allowance
- Approve
- Balance
- Decimals
- decrease allowance
- increase allowance
- Name
- Symbol
- Total Supply
- Transfer 
- Transfer from
